/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
	int a = argp->a;
	int b = argp->b;
	result = a + b;
	printf("Received %d and %d, sending back %d\n",a, b, result);

	return &result;
}
