/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"


void
add_prog_1(char *host, int a, int b)
{
	CLIENT *clnt;
	int  *result_1;
	numbers  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	add_1_arg.a = a;
	add_1_arg.b = b;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}else{
		printf("Result: %d\n", *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

void check_args(int argc, char * argv[]){
    //Έλεγχος για το πλήθος των ορισμάτων
    if (argc != 2) {
        printf("Usage: %s server_host\n", argv[0]);
        exit(EXIT_FAILURE);
    }
}
int user_input(int *num1, int *num2) {
    char input[100];  // Buffer to store the user's input
    char term;        // Variable to check for extra characters

    while (1) {
        printf("Enter two numbers (or 'q' to quit): ");
        
        // Read the full input line
        fgets(input, sizeof(input), stdin);

        // Check if the user wants to quit by entering 'q' alone
        if (input[0] == 'q' && (input[1] == '\n' || input[1] == '\0')) {
            return 0;
        }

        // Check if the input matches the pattern "number number"
        int count = sscanf(input, "%d %d", num1, num2);
        
        if (count == 2) {
            // Successfully read two integers, now check for extra characters
            if (sscanf(input, "%d %d%c", num1, num2, &term) == 3 && term != '\n') {
                printf("Invalid input\n");
                continue;
            }
            return 1;  // Return success if two valid numbers are entered
        } else {
            printf("Invalid input\n");
        }
    }
}
int
main (int argc, char *argv[]){
	char *host;
	int num1, num2;
	
	check_args(argc, argv);
	host = argv[1];

	while (1) {
        // Call the function to get valid input
        int result = user_input(&num1, &num2);

        // If result is 0, the user entered 'q' to quit
        if (result == 0) {
            printf("Exiting client program.\n");
            break;
        }
		add_prog_1 (host, num1, num2);
    }
	exit (0);
}
